apiVersion: v1
kind: Service
metadata:
  namespace: practice-1
  name: nginx-service
  labels:
    part-of: k8s-practice
    componet: web-server
    name: practice-1
    instance: practice-1-1
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
  type: NodePort
