apiVersion: v1
kind: ConfigMap
metadata:
  namespace: practice-1
  name: nginx-config
  labels:
    part-of: k8s-practice
    componet: web-server
    name: practice-1
    instance: practice-1-1
    version: 1.0.0
    managed-by: kubectl
data:
  nginx.conf: |
    events {}

    http {
     server{
       listen 80;
       location / {
         return 200 'Hello from NGINX ConfigMap!';
       }
     }
    }
